accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

tim_app/urls.py
from django.urls import path
from . import views
from tim_app.views import TimeIsMoneygeView, TimeIsMoneygeListView, MorningView, EveningView, HourlyWageView, PaidLeaveView, GeneratePdfView

app_name = 'tim_app'
urlpatterns = [
	path('', TimeIsMoneygeView.as_view(), name='timeismoneyge'),
	path('user/<int:id>', TimeIsMoneygeListView.as_view(), name='timeismoneyge_list'),
	path('morning_add/<int:id>', MorningView.as_view(), name='morning_add'),
	path('evening_add/<int:id>', EveningView.as_view(), name='evening_add'),

	path('detail/<int:overtime_id>', views.detail, name='detail'),
	# path('detail/<int:id>', views.TimeIsMoneygeDetailView.as_view(), name='detail'),

	path('delete/<int:overtime_id>', views.delete, name='delete'),
	path('morning_edit/<int:overtime_id>', views.morning_edit, name='morning_edit'),
	path('evening_edit/<int:overtime_id>', views.evening_edit, name='evening_edit'),
	path('hourly_wage_add/<int:id>', HourlyWageView.as_view(), name='hourly_wage_add'),

	# path('generate_pdf', views.generate_pdf, name='generate_pdf'),
	path('generate_pdf/<int:id>', GeneratePdfView.as_view(), name='generate_pdf'),

	path('paid_leave/<int:id>', PaidLeaveView.as_view(), name='paid_leave'),
	path('paid_leave_delete/<int:paid_leave_id>', views.paid_leave_delete, name='paid_leave_delete'),
	]

time_is_moneyge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tim_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #ログイン用url
    path('accounts/', include('accounts.urls')), #サインアップ用url
    #path('accounts/', include('allauth.urls')),
]

tim_app/models.py
from django.db import models
from django.conf import settings
from accounts.models import CustomUser

# Create your models here.
class Time_is_moneyge(models.Model):
	date = models.DateField(auto_now_add=True)
	morning_word = models.CharField('おはようの一言', max_length=150, null=True, blank=True)
	start_datetime = models.DateTimeField(auto_now_add=True)
	morning_overtime = models.DurationField(null=True)
	evening_word = models.CharField('お疲れ様の一言', max_length=150, null=True, blank=True)
	end_datetime = models.DateTimeField(auto_now_add=True)
	evening_overtime = models.DurationField(null=True)
	overtime = models.DurationField(null=True)
	todays_overtime = models.DurationField(null=True)
	working_time = models.DurationField(null=True)
	user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)

	def __str__(self):
		return str(self.morning_word)

class Hourly_wage(models.Model):
	created_datetime = models.DateTimeField(auto_now_add=True)
	hourly_wage = models.PositiveIntegerField('時給', null=True)
	user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)

	def __str__(self):
		return str(self.hourly_wage)

class Paid_leave(models.Model):
	created_datetime = models.DateTimeField(auto_now_add=True)
	paid_leave_date = models.DateField('有給休暇日', null=True)
	memo = models.CharField('メモ', max_length=300, null=True, blank=True)
	user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)

	def __str__(self):
		return str(self.paid_leave_date)

tim_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Time_is_moneyge, Hourly_wage, Paid_leave

class MorningForm(forms.ModelForm):
	class Meta:
		model = Time_is_moneyge
		fields = {'morning_word'}

class EveningForm(forms.ModelForm):
	class Meta:
		model = Time_is_moneyge
		fields = {'evening_word'}

class HourlyWageForm(forms.ModelForm):
	class Meta:
		model = Hourly_wage
		fields = {'hourly_wage'}

class PaidLeaveForm(forms.ModelForm):
	class Meta:
		model = Paid_leave
		fields = {'memo','paid_leave_date'}
		
	# modelformにplaceholderを入れる
	def __init__(self, *args, **kwargs):
		super(PaidLeaveForm, self).__init__(*args, **kwargs)
		for key, field in self.fields.items():
			if isinstance(field.widget, forms.TextInput) or \
				isinstance(field.widget, forms.Textarea) or \
				isinstance(field.widget, forms.DateInput) or \
				isinstance(field.widget, forms.DateTimeInput) or \
				isinstance(field.widget, forms.TimeInput):
				field.widget.attrs.update({'placeholder': field.label})

		

tim_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from django.db.models import Sum, F
import re
from decimal import Decimal, ROUND_HALF_UP, ROUND_HALF_EVEN
import json
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

from .models import Time_is_moneyge, Hourly_wage, Paid_leave
from .forms import MorningForm, EveningForm, HourlyWageForm, PaidLeaveForm

from django.views import generic, View
from django.contrib import messages

"""weasyprint"""
from django.template.loader import render_to_string
from weasyprint import HTML, CSS
import tempfile
from django.template.loader import get_template
from weasyprint.fonts import FontConfiguration

from itertools import chain #queryset結合
from operator import attrgetter #結合したquerysetをソート

class TimeIsMoneygeView(View):
	def get(self, request, *args, **kwargs):		
		return render(request, 'tim_app/main.html')

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.id == self.kwargs['id'] or user.is_superuser

class TimeIsMoneygeListView(LoginRequiredMixin, OnlyYouMixin, View):
	def get(self, request, *args, **kwargs):
		
		"""ユーザー検証"""
		login_user_id = str(self.request.user.id) #ログインしているユーザーのid
		print("ログインID",login_user_id)
		url_user_id = str(self.kwargs['id']) #urlのid
		print("URLID", url_user_id)
		if login_user_id == url_user_id:

			"""一覧データ取得"""
			morning_list = Time_is_moneyge.objects.filter(user=self.request.user).exclude(morning_overtime__exact = None).order_by('id') 
			evening_list = Time_is_moneyge.objects.filter(user=self.request.user).exclude(evening_overtime__exact = None).order_by('id') 
			
			#querysetの結合
			total_list = sorted(
			chain(morning_list, evening_list),
			key=attrgetter('date')) 
			
			"""現在の時給"""
			try:
				get_current_hourly_wage = Hourly_wage.objects.filter(user=self.request.user).order_by('created_datetime').last() #created_datetimeの日付でソートして最新の時給を取得
				current_hourly_wage_str = str(get_current_hourly_wage) #１行上の型（'tim_app.models.Hourly_wage'）はintに変換できないため、まずstrに変換
				current_hourly_wage = int(current_hourly_wage_str) #strからintに変換
			except:
				current_hourly_wage = 0
			
			"""今日の日付を取得"""
			today = datetime.today() 
			
			"""今月の残業時間"""
			if today.day > 10: #日付が1日から10日以外
				print(type(today.day))
				print(today.day)
				eleventh_of_thismonth = today + relativedelta(day=11) #今月の11日を取得
				print("今月", eleventh_of_thismonth)
				work_of_thismonth = Time_is_moneyge.objects.filter(date__range=(eleventh_of_thismonth, today), user=self.request.user) #11日から今日までのオブジェクトをログインユーザーで取得
				morning_overtime_of_thismonth = work_of_thismonth.aggregate(morning_overtime=Sum('morning_overtime')) #今月の朝の残業時間を集計
				evening_overtime_of_thismonth = work_of_thismonth.aggregate(evening_overtime=Sum('evening_overtime')) #今月の夜の残業時間を集計
				for moot_key, moot_value in morning_overtime_of_thismonth.items(): #keyとvalueに分ける
					morning_total_overtime = moot_value #valueを取得
					for eoot_key, eoot_value in evening_overtime_of_thismonth.items(): #keyとvalueに分ける
						evening_total_overtime = eoot_value #valueを取得
						try:
							total_overtime_of_thismonth = morning_total_overtime + evening_total_overtime #今月の残業時間合計を取得
							minutes, seconds = divmod(total_overtime_of_thismonth.seconds + total_overtime_of_thismonth.days * 86400, 60) #days * 86400で日にちを秒に変換、時間を秒に変換したものを+して60で割って分と秒にわける
							hours, minutes = divmod(minutes, 60) #分を時と分に
							total_overtime_of_thismonth = '{:d}:{:02d}:{:02d}'.format(hours, minutes, seconds) 
						except:
							total_overtime_of_thismonth = 0
			#今日の日付が1日〜10日の場合
			else:
				eleventh_of_one_month_ago = today - relativedelta(months=1, day=11) #一月前の11日を取得
				print("ひと月前", eleventh_of_one_month_ago)
				work_of_thismonth = Time_is_moneyge.objects.filter(date__range=(eleventh_of_one_month_ago, today), user=self.request.user) #11日から今日までのオブジェクトをログインユーザーで取得
				morning_overtime_of_thismonth = work_of_thismonth.aggregate(morning_overtime=Sum('morning_overtime')) #今月の朝の残業時間を集計
				evening_overtime_of_thismonth = work_of_thismonth.aggregate(evening_overtime=Sum('evening_overtime')) #今月の夜の残業時間を集計
				for moot_key, moot_value in morning_overtime_of_thismonth.items(): #keyとvalueに分ける
					morning_total_overtime = moot_value #valueを取得
					for eoot_key, eoot_value in evening_overtime_of_thismonth.items(): #keyとvalueに分ける
						evening_total_overtime = eoot_value #valueを取得
						try:
							total_overtime_of_thismonth = morning_total_overtime + evening_total_overtime #今月の残業時間合計を取得
							minutes, seconds = divmod(total_overtime_of_thismonth.seconds + total_overtime_of_thismonth.days * 86400, 60) #days * 86400で日にちを秒に変換、時間を秒に変換したものを+して60で割って分と秒にわける
							hours, minutes = divmod(minutes, 60) #分を時と分に
							total_overtime_of_thismonth = '{:d}:{:02d}:{:02d}'.format(hours, minutes, seconds)
							print(total_overtime_of_thismonth)
						except:
							total_overtime_of_thismonth = 0

			"""合計の残業金額"""
			try:
				total_overtime_of_thismonth_str = '.'.join(re.split('[,:]', str(total_overtime_of_thismonth))[0:2]) #timedeltaを文字列に変換。dayとsecondをsplit
				total_overtime_of_thismonth_str_hour = '.'.join(re.split('[,:]', str(total_overtime_of_thismonth))[0:1]) #timedeltaを文字列に変換。hourだけ
				total_overtime_of_thismonth_str_minute = '.'.join(re.split('[,:]', str(total_overtime_of_thismonth))[1:2]) #timedeltaを文字列に変換。minuteだけ
				total_overtime_of_thismonth_int_hour = int(total_overtime_of_thismonth_str_hour) * 60 #hourを分に変換
				total_overtime_of_thismonth_int = (total_overtime_of_thismonth_int_hour + int(total_overtime_of_thismonth_str_minute)) / 60 #合計時間を時間に変換
				total_overtime_of_thismonth_float = float(total_overtime_of_thismonth_int) #float型に変換
				total_overtime_amount = total_overtime_of_thismonth_float * current_hourly_wage #合計残業金額を取得
				total_overtime_amount = (Decimal(str(total_overtime_amount)).quantize(Decimal('0'), rounding=ROUND_HALF_UP)) #四捨五入
			except:
				total_overtime_amount = 0

			"""今月の有給"""
			if today.day  > 10:
				eleventh_of_thismonth = today + relativedelta(day=11) #今月の11日を取得
				tenth_of_next_month = today + relativedelta(months=1, day=10) #次月の10日取得
				paid_leave_list = Paid_leave.objects.filter(user=self.request.user, paid_leave_date__range=(eleventh_of_thismonth, tenth_of_next_month)).order_by('paid_leave_date') 
			else:
				eleventh_of_one_month_ago = today - relativedelta(months=1, day=11) #一月前の11日を取得
				tenth_of_this_month = today + relativedelta(day=10) #今月の10日取得
				paid_leave_list = Paid_leave.objects.filter(user=self.request.user, paid_leave_date__range=(eleventh_of_one_month_ago, tenth_of_this_month)).order_by('paid_leave_date') 

			"""月別残業時間（棒グラフ）"""
			latest_year = today.year # 今年
			last_year = today.year - 1 # 去年
			
			# 1月
			lastdata_of_latest_january = Time_is_moneyge.objects.all().filter(date__month=1, user=self.request.user).last() # date__monthの最後のデータ
			if lastdata_of_latest_january != None: # date__monthの最後のデータがNoneではない場合
				if lastdata_of_latest_january.date.year == today.year: # 最後のデータの年と今日の年を比較してイコールの場合
					sort_january = Time_is_moneyge.objects.all().filter(date__year=latest_year, date__month=1, user=self.request.user) #今年でソート
					sort_january = sort_january.aggregate(overtime=Sum('overtime'))
					for sort_january_key, sort_january_value in sort_january.items():
						sort_january = sort_january_value #valueを取得
						minutes, seconds = divmod(sort_january.seconds + sort_january.days * 86400, 60) #days * 86400で日にちを秒に変換、時間を秒に変換したものを+して60で割って分と秒にわける
						hours, minutes = divmod(minutes, 60) #分を時と分に
						sort_january = '{:d}:{:02d}'.format(hours, minutes)
						sort_january = '.'.join(re.split('[:]', str(sort_january)))
				else:
					sort_january = Time_is_moneyge.objects.all().filter(date__year=last_year, date__month=1, user=self.request.user) # 去年でソート
					sort_january = sort_january.aggregate(overtime=Sum('overtime'))
					for sort_january_key, sort_january_value in sort_january.items():
						sort_january = sort_january_value #valueを取得
						minutes, seconds = divmod(sort_january.seconds + sort_january.days * 86400, 60) #days * 86400で日にちを秒に変換、時間を秒に変換したものを+して60で割って分と秒にわける
						hours, minutes = divmod(minutes, 60) #分を時と分に
						sort_january = '{:d}:{:02d}'.format(hours, minutes)
						sort_january = '.'.join(re.split('[:]', str(sort_january)))
			else:
				sort_january = 0
			# 2月					
			lastdata_of_latest_february = Time_is_moneyge.objects.all().filter(date__month=2, user=self.request.user).last() # date__monthの最後のデータ
			if lastdata_of_latest_february != None:
				if lastdata_of_latest_february.date.year == today.year: # 最後のデータの年と今日の年を比較してイコールだったら
					sort_february = Time_is_moneyge.objects.all().filter(date__year=latest_year, date__month=2, user=self.request.user) # 今年でソート
					sort_february = sort_february.aggregate(overtime=Sum('overtime'))
					for sort_february_key, sort_february_value in sort_february.items():
						sort_february = sort_february_value #valueを取得
						minutes, seconds = divmod(sort_february.seconds + sort_february.days * 86400, 60) #days * 86400で日にちを秒に変換、時間を秒に変換したものを+して60で割って分と秒にわける
						hours, minutes = divmod(minutes, 60) #分を時と分に
						sort_february = '{:d}:{:02d}'.format(hours, minutes)
						sort_february = '.'.join(re.split('[:]', str(sort_february)))
				else:
					sort_february = Time_is_moneyge.objects.all().filter(date__year=last_year, date__month=2, user=self.request.user) # 去年でソート
					sort_february = sort_february.aggregate(overtime=Sum('overtime'))
					for sort_february_key, sort_february_value in sort_february.items():
						sort_february = sort_february_value #valueを取得

templates/tim_app/detail.html
{% extends 'base.html' %}
{% load timedelta_filter %}
{% load bootstrap4%}
{% block content %}
{% load static %}

<div class="container">

	<!--一覧に戻る-->
	<div class="row justify-content-center mb-4">
		<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
	
		<!--編集画面へ遷移-->
		{% if overtime_detail.evening_overtime == None %}
		<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:morning_edit' overtime_detail.pk %}">編集画面</a>
		{% else %}
		<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:evening_edit' overtime_detail.pk %}">編集画面</a>
		{% endif %}
		
		<!--削除機能-->
		<form method="post" action="{% url 'tim_app:delete' overtime_detail.pk %}">{% csrf_token %}
			<button type="submit" class="btn btn-primary mr-5" role="button" onclick='return confirm("本当に削除しますか？");'>削除</button>
		</form>
	</div>

	<!--朝の詳細表示-->
	<div class="row justify-content-center lead">
		<div id = "morning_list">
			<ul class="list-unstyled">
				<li>日付　　　　　　　　{{ overtime_detail.date }}</li>
				<li>おはようの一言　　　{{ overtime_detail.morning_word|default:"おはようございます" }}</li>
				<li>出社時間　　　　　　{{ overtime_detail.start_datetime }}</li>
				<li class ="morning_hide">朝の時間外労働　　　{{ overtime_detail.morning_overtime }}</li>
			</ul>
		</div>

		<!--夜の詳細表示-->
		<div id = "evening_list">
			<ul class="list-unstyled">
				<li>日付　　　　　　　　{{ overtime_detail.date }}</li>
				<li>お疲れ様の一言　　　{{ overtime_detail.evening_word|default:"お疲れ様でした" }}</li>
				<li>退社時間　　　　　　{{ overtime_detail.end_datetime }}</li>
				<li class ="evening_hide">夜の時間外労働　　　{{ overtime_detail.evening_overtime }}</li>
			</ul>
		</div>
	</div>
	<!--朝の詳細表示-->
	<!--<div class="row justify-content-center">
		<div id = "morning_list">
			<dl class="row">
				<dt class="col-sm-4 text-right">日付</dt>
				<dd class="col-sm-8 text-center">{{ overtime_detail.date }}</dd>
				<dt class="col-sm-3">おはようの一言</dt>
				<dd class="col-sm-9">{{ overtime_detail.morning_word|default:"おはようございます" }}</dd>
				<dt class="col-sm-3">出社時間</dt>
				<dd class="col-sm-9">{{ overtime_detail.start_datetime }}</dd>
				<dt class ="morning_hide col-sm-3">朝の時間外労働</dt>
				<dd class="col-sm-9">{{ overtime_detail.morning_overtime }}</dd>
			</dl>
		</div>-->

		<!--夜の詳細表示-->
		<!--<div id = "evening_list">
			<dl class="row">
				<dt class="col-sm-3">日付</dt>
				<dd class="col-sm-9">{{ overtime_detail.date }}</dd>
				<dt class="col-sm-3">お疲れ様の一言</dt>
				<dd class="col-sm-9">{{ overtime_detail.evening_word|default:"お疲れ様でした" }}</dd>
				<dt class="col-sm-3">退社時間</dt>
				<dd class="col-sm-9">{{ overtime_detail.end_datetime }}</dd>
				<dt class ="evening_hide col-sm-3">夜の時間外労働</dt>
				<dd class="col-sm-9">{{ overtime_detail.evening_overtime }}</dd>
			</dl>
		</div>
	</div>-->
</div>

{% endblock %}

templates/tim_app/evening_add.html
{% extends 'base.html' %}
{% load bootstrap4%}
{% block content %}
{% load static %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
				</div>
				<form action="{% url 'tim_app:evening_add' user.id %}" method="POST">{% csrf_token %}
					{% bootstrap_form evening_form %}
					<button type="submit" class = "btn btn-primary " role="button">お疲れ様でした！</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/tim_app/evening_edit.html
{% extends 'base.html' %}
{% load bootstrap4%}
{% block content %}
{% load static %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:detail' edit_overtime.id %}">戻る</a>
				</div>
				<form action="{% url 'tim_app:evening_edit' edit_overtime.id %}" method="POST">{% csrf_token %}
					{% bootstrap_form evening_form %}
					<button type="submit" class = "btn btn-primary " role="button">お疲れ様を修正</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/tim_app/exception.html
{% extends 'base.html' %}
{% load timedelta_filter %}
{% load humanize %}
{% block content %}
{% load static %}
<div class="row justify-content-center mb-4">
	<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
</div>
<div class="row justify-content-center mb-4">
<h5>アクセスできません</h5>
</div>
{% endblock %}

templates/tim_app/hourly_wage_add.html
{% extends 'base.html' %}
{% load bootstrap4%}
{% block content %}
{% load static %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
				</div>
				<form action="{% url 'tim_app:hourly_wage_add' user.id %}" method="POST">{% csrf_token %}
					{% bootstrap_form hourly_wage_form %}
					<button type="submit" class = "btn btn-primary " role="button">時給を登録</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/tim_app/main.html
{% extends 'base.html' %}
{% load timedelta_filter %}
{% load humanize %}
{% block content %}
{% load static %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="card-body">
				{% if user.is_authenticated %}
		    	<h3 class="text-center font-weight-bold mb-4" style="color: #666666;">{{ user.last_name }}{{ user.first_name }} さん、こんにちは。</h3>
		    	<div class="row justify-content-center">
		    		<a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'tim_app:timeismoneyge_list' user.id %}">あなたページへ</a>
			        <a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'logout' %}" onclick='return confirm("ログアウトしますか？");'>ログアウト</a>
				    <a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'password_change' %}">パスワード変更</a>
			    </div>
			    {% else %}
			    <h3 class="text-center font-weight-bold mb-4" style="color: #666666;">こんにちは。ゲストさん</h3>
			    <div class="row justify-content-center">
			    	<a class="mr-4 btn btn-lg btn-primary" role="button" href="{% url 'login' %}" >ログイン</a>
			    	<a class="btn btn-lg btn-primary" role="button" href="{% url 'accounts:signup' %}">ユーザー登録</a>
			    </div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/tim_app/morning_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% load static %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
				</div>

				<form action="{% url 'tim_app:morning_add' user.id %}" method="POST">{% csrf_token %}
					{% bootstrap_form morning_form %}
					<button type="submit" class = "btn btn-primary" role="button">おはようございます！</button>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/tim_app/morning_edit.html
{% extends 'base.html' %}
{% load bootstrap4%}
{% block content %}
{% load static %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:detail' edit_overtime.id %}">戻る</a>
				</div>
				<form action="{% url 'tim_app:morning_edit' edit_overtime.id %}" method="POST">{% csrf_token %}
					{% bootstrap_form morning_form %}
					<button type="submit" class = "btn btn-primary " role="button">おはようを修正</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/tim_app/not_evening_register.html
{% extends 'base.html' %}
{% load timedelta_filter %}
{% load humanize %}
{% block content %}
{% load static %}

<div class="row justify-content-center mb-4">
	<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
</div>
<div class="row justify-content-center mb-4">
	<h5>退勤の手続きがされてません！！</h5>
</div>



{% endblock %}

templates/tim_app/not_morning_register.html
{% extends 'base.html' %}
{% load timedelta_filter %}
{% load humanize %}
{% block content %}
{% load static %}

<div class="row justify-content-center mb-4">
	<a class="btn btn-primary mr-4" role="button" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
</div>
<div class="row justify-content-center mb-4">
	<h5>出勤の手続きがされてません！！</h5>
</div>



{% endblock %}

templates/tim_app/paid_leave.html
{% extends 'base.html' %}
{% load bootstrap4%}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}
{% load static %}

<script>
  	$(function () {
      	// 日付は、年-月-日 の形式でお願いする。
      	let dateFormat = 'yy-mm-dd';
      	$('#id_paid_leave_date').datepicker({
          	dateFormat: dateFormat
      	});
  	});
</script>

<!--START PAID LEAVE FORM-->
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 col-md-10 col-sm-12">
			<div class="card-body">
				<div>
					<a class="btn btn-primary w-15 mb-4" href="{% url 'tim_app:timeismoneyge_list' user.id %}">ホームに戻る</a>
				</div>
				<form action="{% url 'tim_app:paid_leave' user.id %}" method="POST">{% csrf_token %}

					<!-- {% bootstrap_form paid_leave_form %} -->

					<!-- {{ paid_leave_form.paid_leave_date|as_crispy_field }}
					{{ paid_leave_form.memo|as_crispy_field }} -->

					<div class= "mb-4">{{ paid_leave_form.paid_leave_date|add_class:'form-control' }}</div>
					<div class= "mb-4">{{ paid_leave_form.memo|add_class:'form-control' }}</div>

					<button type="submit" class = "btn btn-primary " role="button">有給登録</button>
				</form>
			</div>
		</div>
	</div>
</div>
<!--END PAID LEAVE FORM-->

{% endblock %}