accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

tim_app/urls.py
from django.urls import path
from . import views
from tim_app.views import TimeIsMoneygeView, TimeIsMoneygeListView, MorningView, EveningView, HourlyWageView, PaidLeaveView, GeneratePdfView

app_name = 'tim_app'
urlpatterns = [
	path('', TimeIsMoneygeView.as_view(), name='timeismoneyge'),
	path('user/<int:id>', TimeIsMoneygeListView.as_view(), name='timeismoneyge_list'),
	path('morning_add/<int:id>', MorningView.as_view(), name='morning_add'),
	path('evening_add/<int:id>', EveningView.as_view(), name='evening_add'),

	path('detail/<int:overtime_id>', views.detail, name='detail'),
	# path('detail/<int:id>', views.TimeIsMoneygeDetailView.as_view(), name='detail'),

	path('delete/<int:overtime_id>', views.delete, name='delete'),
	path('morning_edit/<int:overtime_id>', views.morning_edit, name='morning_edit'),
	path('evening_edit/<int:overtime_id>', views.evening_edit, name='evening_edit'),
	path('hourly_wage_add/<int:id>', HourlyWageView.as_view(), name='hourly_wage_add'),

	# path('generate_pdf', views.generate_pdf, name='generate_pdf'),
	path('generate_pdf/<int:id>', GeneratePdfView.as_view(), name='generate_pdf'),

	path('paid_leave/<int:id>', PaidLeaveView.as_view(), name='paid_leave'),
	path('paid_leave_delete/<int:paid_leave_id>', views.paid_leave_delete, name='paid_leave_delete'),
	]

time_is_moneyge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tim_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #ログイン用url
    path('accounts/', include('accounts.urls')), #サインアップ用url
    #path('accounts/', include('allauth.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load bootstrap4%}
{% bootstrap_css%}
{% bootstrap_javascript jquery='True'%} 
{% load static %}
<html lang="ja">

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--TITLE-->
		<title>{% block title %}Time Is Moneyge{% endblock %}</title>

		{# --- START CSS --- #}
		<!--BOOTSTRAP-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<!--DATATABLES-->
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
		<!--CSS FOR THIS APP-->
		<link rel="stylesheet" type="text/css" href="{% static 'tim_app/css/tim_app.css' %}">
		<!-- <link rel="stylesheet" type="text/css" href="{% static 'tim_app/css/generate_pdf.css' %}"> -->
		<!-- JQUERY-UI.CSS -->
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

		<!-- google fonts -->
		<!-- <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet"> -->
		<link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
		{# --- END CSS --- #}

		{# --- START JS --- #}
		<!-- CHART.JS -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
		
		{# --- END JS ---#}

	</head>

	<body style="padding-top:4.5rem;"><!--NAVBAR固定に必要-->

		<main>
			<!--START NAVBAR-->
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

				<!--START BRAND TITLE-->
				<div class = "font-weight-bold">
					<a class="navbar-brand text-white" href="{% url 'tim_app:timeismoneyge' %}">Time Is Moneyge</a>
				</div>
				<!--END BRAND TITLE-->

				<!--START TOGGLE-->
				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
    			<span class="navbar-toggler-icon"></span>
  				</button>
  				<!--END TOGGLE-->

  				<!--START NAVIGATION-->
  				<!--START NOW TIME-->
  				<div class="collapse navbar-collapse justify-content-end" id="Navber">
  					<ul class="navbar-nav">
				    	<li class="nav-item">
					        <span id="time" class="font-weight-bold text-white"></span>
					    </li>
					</ul>
				</div>
				<!--END NOW TIME-->
				
				<!--START LOGIN-->
  				<div class="collapse navbar-collapse justify-content-end" id="Navber">
  					{% if user.is_authenticated %}
  					<ul class="navbar-nav">
				      	<li class="nav-item text-white mr-3">
				        	<!-- {{ user.get_username }} さん -->
				        	{{ user.last_name }}{{ user.first_name }} さん
				      	</li>
				    </ul>
  					<ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'logout' %}" onclick='return confirm("ログアウトしますか？");'>ログアウト</a>
				      	</li>
				    </ul>
				    {% else %}
				    <ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'login' %}">ログイン</a>
				      	</li>
				    </ul>
  					<ul class="navbar-nav">
				      	<li class="nav-item">
				        	<a class="nav-link" href="{% url 'accounts:signup' %}">ユーザー登録</a>
				      	</li>
				    </ul>
				    {% endif %}
				</div>
				<!--END LOGNIN-->
				<!--END NAVIGATION-->	

			</nav>
			<!--END NAVBAR-->
			
			<!--START MAIN-->
			<div>
				{% block content %}{% endblock %}
			</div>
			<!--END MAIN-->

		</main>

		<!-- START FOOTER -->
		<footer id="footer" class="page-footer font-small bg-dark mt-4">
		  <!-- START COPYRIGHT -->
		  <div class="footer-copyright text-center py-3 text-white">© <span id="view_today"></span> Copyright:
		    <a class="font-weight-bold" href="{% url 'tim_app:timeismoneyge' %}">Time Is Moneyge</a>
		  </div>
		  <!-- END COPYRIGHT -->

		</footer>
		<!-- END FOOTER -->
		
		<!-- START THISYEAR.JS -->
		<script type="text/javascript">
		document.getElementById("view_today").innerHTML = getToday();

		function getToday() {
			var now = new Date();
			var year = now.getFullYear();
			
			var s = year;
			return s;
		}
		</script>
		<!-- END THISYEAR.JS -->
		
		{# --- START JS --- #}
		<!--tim_app.js-->
		<script type="text/javascript" src="{%static 'tim_app/js/tim_app.js' %}"></script>
		<!--datatables.js-->
		<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/plug-ins/1.10.19/i18n/Japanese.json"></script>
		<!--footerFixed.js-->
		<script type="text/javascript" src="{% static 'tim_app/js/footerFixed.js' %}"></script>
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<!-- JQUERY-UI.JS datepickerに必要-->
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
		{# --- END JS --- #}
		
	</body>

</html>